timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: install-build
    name: us-docker.pkg.dev/cloud-builders/ga/node
    entrypoint: bash
    env:
      - CI=true
      - PNPM_HOME=/workspace/.pnpm
      - PATH=/workspace/.pnpm:$PATH
    args:
      - -c
      - |
        set -euo pipefail

        # Activate the workspace's pnpm version via corepack.
        corepack enable
        corepack prepare pnpm@10.20.0 --activate

        pnpm config set store-dir /workspace/.pnpm-store
        pnpm install --frozen-lockfile
        pnpm build
        pnpm predeploy

  - id: deploy-app-engine
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gcloud app deploy --quiet --project="${PROJECT_ID}"
    waitFor:
      - install-build

cache:
  key: pnpm-store
  paths:
    - .pnpm-store
